### ISSUE TITLE
outdated index?

### ISSUE THREAD

**Issue by BuerFat** [monthyx1337/arrow-gui-hack#1]
where can i update the indexes and where can i find the updated indexes ?
![image](https://user-images.githubusercontent.com/40368944/74361641-35819b00-4dbf-11ea-8c9d-3b297a56dbe4.png)

**Comment by monthyx1337** [comment]
create move index is up to date in the source (24)

**Comment by BuerFat** [comment]
> create move index is up to date in the source (24)

ye i re-dl it and it worked .. not sure on what happened but thank you for the reply
