### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by jackieyiwu** [monthyx1337/arrow-gui-hack#2]
How can i change the text to another font , i didt find any code for the .ttf files

**Comment by monthyx1337** [comment]
renderer.cpp

**Comment by jackieyiwu** [comment]
yes . but as new im confused about the code:
void render::setup() {
	render::fonts::watermark_font = interfaces::surface->font_create();
	render::fonts::esp_font = interfaces::surface->font_create();

	interfaces::surface->set_font_glyph(render::fonts::watermark_font, "Tahoma", 12, 500, 0, 0, font_flags::fontflag_dropshadow);
	interfaces::surface->set_font_glyph(render::fonts::esp_font, "Tahoma", 12, 600, 0, 0, font_flags::fontflag_dropshadow);

wats is the set_font_glpyh  meaning , is it a font ?  and output text Tahoma?

**Comment by monthyx1337** [comment]
isn't it obvious, just read it? also like if you change Tahoma to Verdana the font will be Verdana.
